name: Publish release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number to tag and release'
        required: true
        type: string
      prerelease:
        description: 'Release as pre-release'
        required: false
        type: boolean
        default: false
jobs:
  release-npm:
    runs-on: ubuntu-latest
    environment: main
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use supported Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-22-${{ hashFiles('package-lock.json', 'package.json') }}
      - name: Install dependencies
        run: npm install
      - name: Bump Version
        run: node scripts/bump-version.mjs "${{ inputs.version }}" "${{ github.actor }}"
        env:
          GITHUB_ACTIONS: 'true'
      - name: Push changes
        run: git push origin HEAD:${{ github.ref }}
      - name: Update npm
        run: npm install -g npm@11.16.0
      - name: Publish to npm
        run: npm publish --access public --tag ${{ inputs.prerelease == true && 'next' || 'latest' }} --provenance
      - name: Create release notes
        run: npx @matteo.collina/release-notes -a ${{ secrets.GH_RELEASE_TOKEN }} -t v${{ inputs.version }} -r graphql-composer -o platformatic ${{ github.event.inputs.prerelease == 'true' && '-p' || '' }} -c ${{ github.ref }}
